AWSTemplateFormatVersion: 2010-09-09

Description: |
    This is the web server for Kittens Carousel project. Creating an EC2 instance with a userdata that installs an Apache web server.

Parameters:
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: Name of the key pair that you use for this web server.
  
  MySecurityGroup:
    Description: My security group.    
    Type: AWS::EC2::SecurityGroup::GroupName

Resources:
  KittensCarouselWebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0e731c8a588258d0d
      InstanceType: t2.micro
      KeyName: !Ref KeyPairName
      SecurityGroups: 
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: kittens-cloudformation
      UserData: 
        Fn::Base64: |
          #!/bin/bash
          dnf update -y
          dnf install git httpd -y
          git clone https://github.com/ZXQWAS/Project-101-kittens-carousel-static-website-ec2-CF.git /home/ec2-user/app
          mv /home/ec2-user/app/static-web/* /var/www/html
          systemctl start httpd
          systemctl enable httpd
          
Outputs:
  PublicIPAddress:
    Description: The public IP of my instance.
    Value: !Sub 
    - http://${PublicAddress}
    - PublicAddress: !GetAtt KittensCarouselWebServer.PublicIp
